services:
  web:
    build:
      context: ./webapp
    image: my-webapp
    depends_on:
      - database
    ports:
      - "80:80"
  database:
    build:
      context: ./database
    image: my-db
    environment:
      MYSQL_ROOT_PASSWORD: cases123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: